language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly
before_script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install --dev
script: phpunit -c phpunit.xml.dist --coverage-text
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm
        - php: hhvm-nightly
