parameters:
    redis.manager.class: Euskadi31\Bundle\RedisBundle\Redis\RedisManager
    session.handler.redis.class: Euskadi31\Bundle\RedisBundle\Redis\RedisSessionHandler
services:
    redis.manager:
        class: %redis.manager.class%
        arguments: [%redis%]
    redis:
        class: Redis
        factory_service: redis.manager
        factory_method: getRedis
    session.handler.redis:
        class:     %session.handler.redis.class%
        arguments: [@redis, 10]
