parameters:
    redis.class: Redis
    redis.manager.class: Euskadi31\Bundle\RedisBundle\Redis\RedisManager
    session.handler.redis.class: Euskadi31\Bundle\RedisBundle\Redis\RedisSessionHandler
services:
    redis:
        class: %redis.class%
    redis.manager:
        class: %redis.manager.class%
        arguments: [@redis, %redis%]
    session.handler.redis:
        class:     %session.handler.redis.class%
        arguments: [@redis.manager, 10]
